build:
  image: codemy/ruby:2.3.1
  commands:
    - gem update bundler
    - bundle install --path vendor/bundle
    - bundle exec rake db:create db:schema:load
    - bundle exec rake test

  environment:
    RACK_ENV: test
    RAILS_ENV: test
    SECRET_KEY_BASE: blahblahblah

compose:
  database:
    image: postgres:9.5.1
  redis:
    image: redis:3.0.7
  elasticsearch:
    image: elasticsearch:2.2.0

cache:
  mount:
    - vendor/bundle
    - .git

pipeline:
  docker:
    image: plugins/docker
    username: xcoordinate
    password: ${DOCKER_HUB_PASSWORD}
    email: x.coordinate@gmail.com
    repo: xcoordinate/moviedb
    tag: latest

# publish:
#   docker:
#     image: plugins/docker
#     storage_driver: overlay
#     username: xcoordinate
#     password: ${DOCKER_HUB_PASSWORD}
#     email: x.coordinate@gmail.com
#     repo: bordz/moviedb
#     tag: latest
#     when:
#       branch: master
#
#   docker:
#     image: plugins/docker
#     storage_driver: overlay
#     username: xcoordinate
#     password: ${DOCKER_HUB_PASSWORD}
#     email: x.coordinate@gmail.com
#     repo: bordz/moviedb
#     tag: $$TAG
#     when:
#       event: tag
#
# deploy:
#   rancher:
#     url: http://139.162.43.181:8080/v1/projects/1a5
#     access_key: 331394D5CCCEA7E2BE53
#     secret_key: 6ESn1FhSsK7ptTTLnSyS9LT11RCyQKAgEaWr8pDL
#     service: moviedb/web
#     docker_image: codemy/moviedb:latest
#     when:
#       branch: master
#
#   rancher:
#     url: http://139.162.43.181:8080/v1/projects/1a5
#     access_key: 331394D5CCCEA7E2BE53
#     secret_key: 6ESn1FhSsK7ptTTLnSyS9LT11RCyQKAgEaWr8pDL
#     service: moviedb/worker
#     docker_image: codemy/moviedb:latest
#     when:
#       branch: master
#
#   rancher:
#     url: http://139.162.43.181:8080/v1/projects/1a27
#     access_key: 11DA23F40759A1A305F5
#     secret_key: xvidTFM5aKdFVFkBBgQvbiYqMcS99NR1eUTZAJG1
#     service: moviedb/web
#     docker_image: codemy/moviedb:$$TAG
#     when:
#       event: tag
#
#   rancher:
#     url: http://139.162.43.181:8080/v1/projects/1a27
#     access_key: 11DA23F40759A1A305F5
#     secret_key: xvidTFM5aKdFVFkBBgQvbiYqMcS99NR1eUTZAJG1
#     service: moviedb/worker
#     docker_image: codemy/moviedb:$$TAG
#     when:
#       event: tag
